apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: zainab11/node-web-app:latest
    imagePullPolicy: Never
    name: nodewebapp
    ports:
    - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  